woowacourse-teams/2023-haru-study

.github/workflows/backend-build-test.yml
- close #23 
라벨 id 확인하기 위한 workflow 작성
=> [BE] CI 워크플로우를 작성한다

.github/workflows/frontend-build-test.yml
=> [FE] CI 워크플로우를 작성

.github/workflows/backend-build-test.yml
- close #29 
- ci 빌드 환경을 Java 17로 설정
- 빌드 결과 slack 알림 추가
=> [BE] ci빌드 환경 셋팅, 결과를 slack알림 추가

.github/workflows/frontend-build-test.yml
- close #32
- 슬랙 알림 추가 스크립트 작성 완료
=> [FE] CI 성공여부 slack 알림 추가

frontend/package.json, frontend/src/App.tsx, frontend/src/index.tsx, frontend/src/router/index.tsx, frontend/yarn.lock
#34 
close #34
react-router-dom 설치 및 라우터 기본 설정
=> [FE] page routing 기본 설정

frontend/__test__/example.test.tsx, frontend/jest.config.json, frontend/package.json, frontend/src/App.tsx, frontend/yarn.lock
=> [FE] 테스트용 테스트 코드 작성

frontend/src/App.tsx
=> [FE] 테스트 코드 수정

backend/build.gradle, backend/src/main/java/harustudy/backend/entity/Member.java, backend/src/main/java/harustudy/backend/entity/MemberProgress.java, backend/src/main/java/harustudy/backend/entity/ParticipantCode.java, backend/src/main/java/harustudy/backend/entity/Pomodoro.java, backend/src/main/java/harustudy/backend/entity/PomodoroProgress.java, backend/src/main/java/harustudy/backend/entity/Study.java, backend/src/main/java/harustudy/backend/entity/StudyStatus.java, backend/src/main/java/harustudy/backend/entity/Version.java, backend/src/main/resources/application.properties
closed #72
- DB 테이블 설계 기반 기본 엔티티 코드 작성
=> [BE] 엔티티 설계

jenkinsfiles/backend-prod
- close #55 
-  빌드 및 스프링 서버 실행하는 파이프라인 구축완료입니다.
=> [BE] 젠킨스 publish over ssh 사용한 배포 파이프라인 구축💪 

backend/src/main/java/harustudy/backend/entity/Member.java, backend/src/main/java/harustudy/backend/entity/MemberRecord.java, backend/src/main/java/harustudy/backend/entity/ParticipantCode.java, backend/src/main/java/harustudy/backend/entity/Pomodoro.java, backend/src/main/java/harustudy/backend/entity/PomodoroProgress.java, backend/src/main/java/harustudy/backend/entity/PomodoroRecord.java, backend/src/main/java/harustudy/backend/entity/Study.java, backend/src/main/java/harustudy/backend/entity/TemplateVersion.java
- close #76 
- 엔티티 설계 변경 및 네이밍 변경
=> [BE] 엔티티 설계 수정

frontend/src/components/common/Input/Input.stories.tsx, frontend/src/components/common/Input/Input.tsx, frontend/src/hooks/useId.ts, frontend/src/styles/theme.ts
=> [FE] Input 컴포넌트 구현

jenkinsfiles/frontend-prod
- closed #86
- 테스트 및 빌드 후 빌드 파일 배포 서버에 옮긴 뒤 배포하는 스크립트 작성 완료
=> [FE] 젠킨스 publish over ssh 사용한 배포 파이프라인 구축

.github/workflows/backend-build-test.yml
- closed #79 
- distribution을 temurin -> corretto로 변경
=> [BE] Github Action 빌드 환경 변경 #79

frontend/src/components/common/Select/Select.stories.tsx, frontend/src/components/common/Select/Select.tsx, frontend/src/components/common/Select/SelectContext.tsx, frontend/src/components/common/Select/SelectItem.tsx, frontend/src/components/common/Select/SelectList.tsx, frontend/src/components/common/Select/SelectTrigger.tsx, frontend/src/types/dom.ts, frontend/src/utils/domEventHandler.ts
- closed #96 
- Select 컴포넌트를 합성 컴포넌트로 구현
- 외부에서 onChange 이벤트로 Select 내부에 있는 value를 알 수 있도록 해주는 composeEventHandler 구현
=> [FE] Select 컴포넌트 구현

frontend/src/components/common/Menu/Menu.tsx, frontend/src/components/common/Menu/MenuItem.tsx
closed #105
- useDisplay 훅을 사용하여 로직을 간소화 한다.
=> [FE] Menu Component Refactoring

frontend/src/components/common/Tabs/TabList.tsx, frontend/src/components/record/AnswerQuestion.tsx, frontend/src/components/record/RecordContents.tsx, frontend/src/components/record/StudyInformation.tsx
closed #131 
- $ prefix 추가
- isLoading
- isSelected
- iconBackgroundColor
=> [FE] Record Page $ prefix 추가

backend/build.gradle, backend/src/main/resources/application.yml
=> [BE] 스웨거 적용

backend/src/main/java/harustudy/backend/content/domain/PomodoroContent.java, backend/src/main/java/harustudy/backend/content/service/ContentService.java, backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java, backend/src/main/java/harustudy/backend/room/domain/Room.java, backend/src/main/java/harustudy/backend/room/service/RoomService.java, backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java, backend/src/test/java/harustudy/backend/participantcode/service/ParticipantCodeServiceTest.java, backend/src/test/java/harustudy/backend/room/service/RoomServiceTest.java
closed #120 
- progress가 생성될 때 초기 content가 함께 생성되도록 수정
- cascade를 사용하지 않도록 변경
=> [BE] 스터디 멤버 등록 후 첫 계획 작성 시 member_content가 생성되지 않는 문제 

backend/build.gradle, backend/src/main/java/harustudy/backend/HaruStudyApplication.java, backend/src/main/java/harustudy/backend/content/domain/PomodoroContent.java, backend/src/main/resources/application.yml, backend/src/main/resources/db/migration/V1.0__init.sql
- closed #123 
- DDL 형상관리를 위한 flyway 도입
=> [BE] DDL 형상관리를 위한 flyway 도입

.gitmodules, backend/build.gradle, backend/src/main/resources/application.yml
- closed: #139 
- mysql 의존성 추가
- 서브모듈 설정
=> [BE] MySQL 드라이버 추가 의존성 추가

backend/build.gradle
- closed #142 
- Flyway Mysql 의존성 추가
=> [BE] Flyway Mysql 의존성 추가

backend/src/main/java/harustudy/backend/content/domain/PomodoroContent.java, backend/src/main/java/harustudy/backend/content/domain/TemplateVersion.java, backend/src/main/resources/db/migration/V1.1__delete-template-version.sql, backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java, backend/src/test/java/harustudy/backend/content/repository/MemberContentRepositoryTest.java, backend/src/test/java/harustudy/backend/content/service/ContentServiceTest.java, backend/src/test/java/harustudy/backend/integration/IntegrationTest.java, backend/src/test/java/harustudy/backend/progress/service/ProgressServiceTest.java
closed #145 
- template version 삭제
=> [BE] template version 삭제

frontend/src/components/common/Select/Select.tsx, frontend/webpack.config.js
closed #147 
-  Select Components out side Click 적용
=> [FE] Select Components Background Click

frontend/__test__/StudyMakingPage.test.tsx, frontend/src/components/common/Header/Header.tsx, frontend/src/components/templates/StudyInfoFormLayout.tsx, frontend/src/pages/StudyRecord.tsx, frontend/webpack.config.js
closed #144 
- Header Components 분리
- 테스트코드 수정
=> [FE] Header Components

frontend/src/api/index.ts, frontend/src/hooks/board/useStudyBoard.ts, frontend/src/mocks/handlers/index.ts, frontend/src/mocks/handlers/studyBoardHandler.ts, frontend/src/types/study.ts
=> [ALL] api url 프로토콜 버그 수정

frontend/src/api/index.ts, frontend/src/components/board/RetrospectForm/RetrospectForm.tsx
closed #153 
- 잘못된 api url 요청 수정
- 진행 페이지 -> 기록 페이지 라우팅 관련 수정
=> [ALL] 잘못된 api url 수정 및 진행 페이지 라우팅 버그 수정

backend/src/main/java/harustudy/backend/progress/dto/RoomAndProgressStepResponse.java, backend/src/test/java/harustudy/backend/progress/service/ProgressServiceTest.java
- closed: #155 
- 메타데이터 step을 소문자로 변경해서 반환한도록 변경
=> [BE] 메타데이터 step을 소문자로 변경해서 반환한도록 변경

frontend/src/components/record/MemberRecord.tsx, frontend/src/mocks/handlers/studyRecordHandlers.ts
closed #157 
- MemberContent type refactoring
=> [FE] MemberContent type refactoring

frontend/src/api/index.ts, frontend/src/components/studyMaking/StudyMakingForm.tsx, frontend/src/hooks/board/usePlanningForm.ts, frontend/src/hooks/board/useRetrospectForm.ts, frontend/src/hooks/board/useStudyingForm.ts
- closed #159
- closed #160 
- 명세서 동기화 문제, 프로퍼티 nickname에서 name으로 변경.
- 요청 시 timePerCycle, totalCycle value 반대로 보내는거 변경.
- content-type 추가
=> [FE] 개설하기 요청 버그

frontend/src/api/index.ts, frontend/src/components/board/GuideContents/GuideContents.tsx, frontend/src/components/board/StudyingForm/StudyingForm.tsx, frontend/src/hooks/board/useStudyingForm.ts
closed #163 
- 학습 목표, 개설하기, 참여하기 api 데이터 형식 수정
=> [FE] 학습 목표, 개설하기, 참여하기 api 데이터 형식 수정

backend/src/main/java/harustudy/backend/config/OpenApiConfiguration.java
=> [BE] 스웨거 ip 설정

frontend/src/hooks/fetch/useParticipantCode.ts, frontend/src/mocks/handlers/checkParticipantCodeHandlers.ts
- closed #166
- nickName에서 nickname으로 변경
=> [FE] 참여 코드 인증 api 요청 로직 수정

frontend/.gitignore, jenkins/frontend-prod.jenkinsfile
- closed #174
- 스토리북 빌드 및 파일 딜리버리 스크립트 젠킨스 파일에 작성
- nginx config 배포 설정
=> [FE] 스토리북 배포

jenkins/frontend-prod.jenkinsfile
- closed #181 
- step -> steps로 변경
=> [FE] 스토리북 배포 스크립트 오탈자 수정

frontend/src/components/board/StudyingForm/StudyingForm.tsx
#172 
- 스터디 진행페이지 학습 단계 목표 순서 다르게 나오는 문제
=> [FE] 스터디 진행페이지 학습 단계 목표 순서 다르게 나오는 문제

backend/src/main/java/harustudy/backend/content/domain/PomodoroContent.java, backend/src/main/java/harustudy/backend/member/controller/MemberController.java, backend/src/main/java/harustudy/backend/member/dto/NicknameResponse.java, backend/src/main/java/harustudy/backend/participantcode/controller/ParticipantCodeController.java, backend/src/main/java/harustudy/backend/participantcode/dto/FindRoomRequest.java, backend/src/main/java/harustudy/backend/participantcode/dto/FindRoomResponse.java, backend/src/main/java/harustudy/backend/room/controller/RoomController.java, backend/src/main/java/harustudy/backend/room/dto/ReParticipateRequest.java, backend/src/main/java/harustudy/backend/room/dto/ReparticipatedRequest.java
- closed #173 
- 스터디 코드 인증 및 스터디 참여 Swagger API 변경사항 업데이트
=> [BE] 스터디 코드 인증 및 스터디 참여 Swagger API 변경사항 업데이트

jenkins/frontend-prod.jenkinsfile
=> [FE] 스토리북 배포 스크립트 실행시키는 젠킨스 스크립트 작성

backend/src/main/java/harustudy/backend/room/controller/RoomController.java
-closed: #191 
- 멤버 생성시 ID 반환하지 않는 문제 수정
=> [BE] 멤버 생성시 ID 반환하지 않는 문제 수정

frontend/src/components/preparation/ParticipationCodeInput/ParticipationCodeInput.tsx
closed #193 
- 스터디 참여시 Content-Type 추가
=> [FE] 스터디 참여시 Content-Type 추가

backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java, backend/src/test/java/harustudy/backend/progress/domain/PomodoroProgressTest.java
- closed #196 
- 한 사이클의 스터디가 종료되었을 때 사이클 수가 늘어나지 않는 문제 해결
=> [BE] 한 사이클의 스터디가 종료되었을 때 사이클 수가 늘어나지 않는 문제

frontend/src/hooks/board/usePlanningForm.ts
closed #203 
- alert 메시지 띄어쓰기 수정
=> [FE] alert 메시지 띄어쓰기 수정

frontend/__test__/StudyMakingPage.test.tsx, frontend/src/components/board/RetrospectForm/RetrospectForm.tsx, frontend/src/components/board/StudyingForm/StudyingForm.tsx, frontend/src/components/common/Header/Header.tsx, frontend/src/components/landing/Contents.tsx, frontend/src/components/preparation/MemberRegister/MemberRegister.tsx, frontend/src/components/preparation/MemberRestart/MemberRestart.tsx, frontend/src/components/preparation/ParticipationCodeInput/ParticipationCodeInput.tsx, frontend/src/components/studyMaking/StudyMakingForm.tsx, frontend/src/constants/routes.ts, frontend/src/pages/CreateStudy.tsx, frontend/src/pages/StudyBoard.tsx, frontend/src/pages/StudyParticipant.tsx, frontend/src/router/index.tsx
- closed #179
- 라우터 url 상수화 및 적용
=> [FE] 라우터 상수화

frontend/.eslintrc, frontend/src/components/board/GuideContents/GuideContents.tsx, frontend/src/components/board/Sidebar/Sidebar.tsx, frontend/src/components/board/StudyingForm/StudyingForm.tsx, frontend/src/components/board/Timer/Timer.tsx, frontend/src/components/common/Accordion/Accordion.tsx, frontend/src/components/common/Accordion/AccordionContext.tsx, frontend/src/components/common/Accordion/AccordionHeader.tsx, frontend/src/components/common/Accordion/AccordionItem.tsx, frontend/src/components/common/Accordion/AccordionPanel.tsx, frontend/src/components/common/Button/Button.tsx, frontend/src/components/common/CircularProgress/CircularProgress.tsx, frontend/src/components/common/Input/Input.tsx, frontend/src/components/common/Menu/Menu.tsx, frontend/src/components/common/Menu/MenuItem.tsx, frontend/src/components/common/QuestionTextarea/QuestionTextarea.tsx, frontend/src/components/common/Select/Select.tsx, frontend/src/components/common/Select/SelectItem.tsx, frontend/src/components/common/Select/SelectList.tsx, frontend/src/components/common/Select/SelectTrigger.tsx, frontend/src/components/common/Tabs/TabItem.tsx, frontend/src/components/common/Tabs/Tabs.tsx, frontend/src/components/common/Tabs/TabsContext.tsx, frontend/src/components/common/Typography/Typography.tsx, frontend/src/hooks/board/useStudyBoard.ts, frontend/src/hooks/board/useStudyingForm.ts, frontend/src/utils/domEventHandler.ts
closed #212 
- eslint type import 적용
- eslint alias 순서 변경
=> [FE] eslint type import 적용 및 alias 순서 변경

jenkins/frontend-prod.jenkinsfile
- closed #216 
- execCommand 삭제
=> [FE] 스토리북 배포 젠킨스 스크립트 수정

frontend/src/components/board/Sidebar/Sidebar.tsx
closed #204 
- 학습 진행회고 페이지에서 실제 사용자가 설정한 시간이 안보이는 문제 수정
=> [FE] Sidebar 문구 스터디 시간에 따라 유동적으로 바뀌도록 수정

frontend/src/components/create/CreateStudyForm/CreateStudyForm.tsx
- closed #242
- 예상 시간 텍스트 로직 변경
=> [FE] 예상 시간 텍스트 수정

frontend/src/api/index.ts, frontend/src/components/board/Sidebar/Sidebar.tsx, frontend/src/components/board/Timer/Timer.tsx, frontend/src/components/common/Button/Button.tsx, frontend/src/components/common/QuestionTextarea/QuestionTextarea.tsx, frontend/src/components/common/Typography/Typography.tsx, frontend/src/hooks/board/useTimer.ts, frontend/src/utils/http.ts
closed #239 
- 마우스 없이 키보드로만 스터디 가능하도록 구현
- 요소 별 aria-label 적용
- http post 함수 로직 수정
https://github.com/woowacourse-teams/2023-haru-study/assets/73513965/7580cf49-798a-41ca-85f4-32e743c7e3d7
=> [FE] 스터디 진행 페이지 웹 접근성

frontend/src/api/index.ts, frontend/src/pages/StudyPreparation.tsx
- closed #246
- 준비 페이지 로딩 스피너 추가
=> [FE] 참여하기 페이지 접근시 로딩 스피너 추가

frontend/src/components/common/Input/Input.tsx, frontend/src/components/create/CreateStudyForm/CreateStudyForm.tsx, frontend/src/components/preparation/MemberRegister/MemberRegister.tsx, frontend/src/components/preparation/ParticipationCodeCopier/ParticipationCodeCopier.tsx, frontend/src/components/preparation/ParticipationCodeInput/ParticipationCodeInput.tsx
- closed #250
- bottom text 밀림 현상 해결
- 10글자 제한 maxlength 추가
=> [FE]  Input 컴포넌트 UI/UX 개선

backend/build.gradle, backend/src/main/resources/application.yml
- closed #292 
- 프로메테우스 메트릭 수집을 위한 gradle 및 yml 설정 추가
=> [BE] Prometheus gradle 설정

frontend/src/hooks/board/useTimer.ts
closed #269
closed #278 
- 타이머 시간 음수로 표기되는 버그 수정
=> [FE] 타이머 시간 음수로 표기되는 버그 수정

frontend/src/components/common/Menu/Menu.stories.tsx, frontend/src/components/common/Menu/Menu.tsx, frontend/src/components/common/Menu/MenuItem.tsx, frontend/src/components/landing/LandingContents/LandingContents.tsx
closed #288 
- 메뉴 컴포넌트 trigger 프롭스 기능 추가
- 메뉴 컴포넌트 bottomSeparator 기능, Props 추가
- SeparatorMenu 스토리 추가
=> [FE] 메뉴 컴포넌트 trigger 프롭스 기능 추가

backend/src/main/resources/application.yml, backend/src/main/resources/default-appender.xml, backend/src/main/resources/error-appender.xml, backend/src/main/resources/http-appender.xml
- #298 
-  actuator 엔드포인트로 logfile 추가
=> [BE] logback 로그 actuator 관련 설정

frontend/.gitignore, frontend/package.json, frontend/src/App.tsx, frontend/src/api/index.ts, frontend/src/constants/routes.ts, frontend/src/contexts/MemberInfoProvider.tsx, frontend/src/mocks/handlers/authHandler.ts, frontend/src/mocks/handlers/index.ts, frontend/src/pages/Auth.tsx, frontend/src/pages/Login.tsx, frontend/src/router/index.tsx, frontend/src/types/api.ts, frontend/src/types/auth.ts, frontend/src/types/member.ts, frontend/src/utils/getUrlQuery.ts, frontend/src/utils/http.ts, frontend/src/utils/params.ts, frontend/webpack.config.js, frontend/yarn.lock
closed  #289 
- 로그인 페이지 추가
- OAuth 페이지 추가
- OAuth 관련 MSW 구현
- webpack Dotenv 플러그인 설정
=> [FE] OAuth 기능 구현

backend/src/main/resources/application-develop.yml, backend/src/main/resources/application-production.yml, backend/src/main/resources/application.yml
- closed: #313 
- 개발 서버, 프로덕션 서버, 로컬 서버 프로파일 분리
=> [BE] 운영 및 개발 서버 DB 분리

backend/src/main/resources/application-develop.yml
- closed: #317 
- flyway 설정 제거 및 프로파일 문제 해결
=> [BE] 개발서버 flyway 설정 변경 및 프로파일 문제 해결

frontend/package.json, frontend/src/pages/Login.tsx, frontend/webpack.common.js, frontend/webpack.dev.js, frontend/webpack.prod.js, frontend/yarn.lock
closed #290 
- 웹팩 환경 분리
- REDIRECT_URI 변경
=> [FE] 웹팩 환경(prod, dev) 설정

backend/src/main/java/harustudy/backend/common/ExceptionMapper.java, backend/src/main/java/harustudy/backend/participantcode/exception/ParticipantCodeExpiredException.java
- closed: #321 
- 에러코드 정의(도메인별로 100번씩 잘랐습니다)
- `ParticipantCode` 같은 경우, API V2에서는 `Room` 하위로 들어갈 개념이므로 에러코드도 같은 대역으로 분류했습니다.
- Ref #312 와 연계되는 내용입니다.
=> [BE] 에러코드 정의

backend/src/main/java/harustudy/backend/config/swagger/SwaggerConfig.java
close #323 
pr #312 의 `SwaggerConfig`를 조금 더 리팩토링해서 제안해봅니다~
기존 PR은 테오, 마코가 한 거라 거기에 commit하긴 애매해서 아예 새로 만들었어요
이왕 깔끔하게 만드는거 조금 더 신경쓰면 예쁠 것 같아서요!
변경 사항은 메서드 순서 재정렬 및 
try 구문의 내용 간소화, 메서드 분리 등을 추가적으로 했습니다!
확인해보시고 괜찮으면 #312 가 닫히기 전에 이걸 머지시키고 #312 도 머지하면 될 것 같아요!
ref #323 #310 
이런 식으로 나오는데 목표하신대로가 맞겠죠? 나중에 확인 한번 부탁드립니다~
=> [BE] SwaggerConfig 메서드 분리 및 순서 재정렬

backend/src/main/java/harustudy/backend/auth/controller/AuthController.java, backend/src/main/java/harustudy/backend/common/ExceptionMapper.java, backend/src/main/java/harustudy/backend/common/SwaggerExceptionResponse.java, backend/src/main/java/harustudy/backend/config/swagger/OpenApiConfiguration.java, backend/src/main/java/harustudy/backend/config/swagger/SwaggerConfig.java, backend/src/main/java/harustudy/backend/content/controller/PomodoroContentControllerV2.java, backend/src/main/java/harustudy/backend/member/controller/MemberControllerV2.java, backend/src/main/java/harustudy/backend/participantcode/exception/ParticipantCodeExpiredException.java, backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressControllerV2.java, backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressServiceV2.java, backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomControllerV2.java
- closed: #310
- 스웨거 예외 응답 전용 커스텀 어노테이션 추가
- 스웨거 상세 명세 추가
=> [BE] 스웨거 예외 응답 명세 추가

backend/src/main/java/harustudy/backend/content/controller/PomodoroContentControllerV3.java, backend/src/main/java/harustudy/backend/content/dto/WritePlanRequestV3.java, backend/src/main/java/harustudy/backend/content/dto/WriteRetrospectRequestV3.java, backend/src/main/java/harustudy/backend/member/controller/MemberControllerV3.java, backend/src/main/java/harustudy/backend/member/dto/GuestRegisterRequest.java, backend/src/main/java/harustudy/backend/member/dto/MemberResponseV3.java, backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressRequestV3.java, backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressResponseV3.java, backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressesResponseV3.java, backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomControllerV2.java, backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomControllerV3.java, backend/src/main/java/harustudy/backend/room/dto/PomodoroRoomResponseV3.java, backend/src/main/java/harustudy/backend/room/dto/PomodoroRoomsResponseV3.java
close #329 
인증 및 개인화 기능 관련 api swagger 문서화
=> [BE] 백엔드 인가 관련 API Swagger 문서화

backend/src/main/java/harustudy/backend/content/controller/PomodoroContentControllerV2.java, backend/src/main/java/harustudy/backend/content/controller/PomodoroContentControllerV3.java, backend/src/main/java/harustudy/backend/content/dto/WritePlanRequestV3.java, backend/src/main/java/harustudy/backend/content/dto/WriteRetrospectRequestV3.java, backend/src/main/java/harustudy/backend/member/controller/MemberControllerV2.java, backend/src/main/java/harustudy/backend/member/controller/MemberControllerV3.java, backend/src/main/java/harustudy/backend/member/dto/GuestRegisterRequest.java, backend/src/main/java/harustudy/backend/member/dto/MemberResponseV3.java, backend/src/main/java/harustudy/backend/participantcode/controller/ParticipantCodeController.java, backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressControllerV2.java, backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressControllerV3.java, backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressRequestV3.java, backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressResponseV3.java, backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressesResponseV3.java, backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomControllerV2.java, backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomControllerV3.java, backend/src/main/java/harustudy/backend/room/dto/PomodoroRoomResponseV3.java, backend/src/main/java/harustudy/backend/room/dto/PomodoroRoomsResponseV3.java
=> [BE] 백엔드 인가 관련 API Swagger 문서화2

backend/src/main/java/harustudy/backend/auth/dto/AuthMember.java, backend/src/main/java/harustudy/backend/content/controller/PomodoroContentController.java, backend/src/main/java/harustudy/backend/content/service/PomodoroContentService.java, backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java, backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java
close #346 
Contents 조회 권한이 있는 사용자는 같은 room에 있는 사용자로 제한
Plan, Retrospect 등록 권한이 있는 사용자는 해당 Progress의 소유자로 제한
=> [BE] Contents 관련 인가 기능 추가

backend/src/main/java/harustudy/backend/auth/dto/AuthMember.java, backend/src/main/java/harustudy/backend/content/controller/PomodoroContentController.java, backend/src/main/java/harustudy/backend/content/service/PomodoroContentService.java, backend/src/main/java/harustudy/backend/member/repository/MemberRepository.java, backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java, backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java, backend/src/main/java/harustudy/backend/progress/dto/ParticipateStudyRequest.java, backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressRequest.java, backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressResponse.java, backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressesResponse.java, backend/src/main/java/harustudy/backend/progress/repository/PomodoroProgressRepository.java, backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java, backend/src/main/java/harustudy/backend/room/repository/PomodoroRoomRepository.java, backend/src/test/java/harustudy/backend/progress/domain/PomodoroProgressTest.java, backend/src/test/java/harustudy/backend/progress/service/PomodoroProgressServiceTest.java
- closed #335 
- MemberProgress 관련 인가 기능 작성 및 테스트
=> [BE] PomdoroProgress 관련 인가 기능 추가 

frontend/.eslintrc, frontend/jest.config.json, frontend/src/errors/index.ts, frontend/src/types/api.ts, frontend/src/utils/http.ts, frontend/tsconfig.paths.json, frontend/webpack.common.js
closed #349 
- API 통신 커스텀 에러 구현
- http get, post 함수 커스텀 에러 적용
=> [FE] API 통신 커스텀 에러

backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java
=> [BE] Progress 관련 Exception 문서화

backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomController.java
=> [BE] Room 관련 Exception 문서화

backend/src/main/java/harustudy/backend/auth/controller/AuthController.java, backend/src/main/java/harustudy/backend/auth/dto/TokenResponse.java, backend/src/main/java/harustudy/backend/auth/exception/RefreshTokenCookieNotExistsException.java, backend/src/main/java/harustudy/backend/auth/service/AuthService.java, backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java, backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java
- close #354 
- 스터디 참여 시 사이클 수에 맞는 컨텐츠를 생성한다.
=> [BE] 스터디 참여 시 콘텐츠 생성 기능

backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java
- close #364 
- Location 헤더 수정(v3 제거)
=> [BE] Locaiton header 자원 URI 수정 

backend/src/main/java/harustudy/backend/auth/AuthInterceptor.java, backend/src/main/java/harustudy/backend/config/WebMvcConfig.java
- close #372 
- CORS 설정 및 Preflight 설정
=> [BE] CORS 및 preflight 설정

backend/src/main/java/harustudy/backend/auth/AuthInterceptor.java, backend/src/main/java/harustudy/backend/config/WebMvcConfig.java, backend/src/test/resources/application.yml
- close #372 
- CORS 설정이 제대로 인식되지 않던 문제 해결
=> [BE] AllowOrigin이 제대로 인식되지 않던 문제 해결

frontend/src/assets/icons/ResetIcon.tsx, frontend/src/components/common/Accordion/AccordionSkeleton.tsx, frontend/src/components/record/MemberRecord/MemberRecord.tsx, frontend/src/components/record/MemberRecordList/MemberRecordList.tsx, frontend/src/components/record/RecordContents/RecordContents.tsx, frontend/src/hooks/record/useStudyRecord.ts
closed #352 
- 스터디 Progress Cycle 미완료시 UI 개선
- 스터디 Recrod Reset Button 추가
=> [FE] Study Record Page 기능 개선

frontend/src/hooks/participation/useCheckProgresses.ts, frontend/src/hooks/participation/useRegisterProgress.ts, frontend/src/mocks/handlers/authHandler.ts, frontend/src/types/member.ts
- 기존 `id`로 필드명 해줬던 것 `memberId`로 변경
=> [FE] memberId 필드명 수정

frontend/src/api/index.ts, frontend/src/components/record/StudyRecordContents/StudyRecordContents.tsx, frontend/src/contexts/MemberInfoProvider.tsx, frontend/src/mocks/handlers/authHandler.ts
closed #390 
- `api/me` 로 api주소 수정
- MemberInfoProvider fetching 로직 수정
- 누락된 ResetButton 구현
=> [FE] 유저 정보 불러오기 리팩터링

backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
- close #395 
- 로그인 시 설정한 쿠키가 브라우저 창 종료 시 삭제되는 문제 해결
=> [BE] 로그인 시 설정한 쿠키가 브라우저 창 종료 시 삭제되는 문제

backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java
- close #400 
- 스터디 참여할 때의 검증 로직을 수정한다.
=> [BE] 스터디 참여할 때의 검증 로직 수정

backend/src/main/resources/logback-spring.xml
- close #322 
- 로그 시간을 KST를 기준으로 기록하도록 설정했습니다.
=> [BE] 서버에서 발생하는 로그 시간이 현재 시간과 일치하지 않는 문제

backend/src/main/resources/db/migration/V1.1__add-auth.sql, backend/src/test/resources/application.yml
- closed #404 
- 1.1 flyway 업데이트
=> [BE] 1.1.0 버전에 맞는 flyway schema 추가

frontend/src/assets/icons/ArrowIcon.tsx, frontend/src/components/board/PlanningForm/PlanningForm.tsx, frontend/src/components/board/RetrospectForm/RetrospectForm.tsx, frontend/src/components/board/StudyingForm/StudyingForm.tsx, frontend/src/components/board/Timer/Timer.tsx, frontend/src/components/common/Button/Button.tsx, frontend/src/components/common/QuestionAnswer/QuestionAnswer.tsx, frontend/src/components/common/QuestionTextarea/QuestionTextarea.tsx, frontend/src/components/common/Typography/Typography.tsx, frontend/src/components/landing/Hero/Hero.tsx, frontend/src/hooks/board/useRetrospectForm.ts, frontend/src/pages/Landing.tsx
closed #402
- 선택 질문 숨기기 기능
- 랜딩 페이지 히어로 이미지 레이아웃 재설정
- QuestionAnswer 컴포넌트 개행 적용 안되는 문제 수정
- Typography 폰트 사이즈 수정
=> [FE] 선택 질문 숨기기(토글) 기능 및 여러 디자인 수정

backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java
close #416
- `/api/studies/{studyId}/progresses/{progressId}`에 대한 swagger 명세 정의
=> [BE] progress delete api swagger 문서 추가 #416

frontend/src/components/board/GuideModal/GuideModal.tsx, frontend/src/components/board/PlanningForm/PlanningForm.tsx, frontend/src/components/board/StepContents/StepContents.tsx, frontend/src/components/common/QuestionTextarea/QuestionTextarea.tsx, frontend/src/constants/study.ts, frontend/src/mocks/handlers/index.ts, frontend/src/pages/StudyBoard.tsx
closed #403 
- 질문 가이드 기능 구현
- 회고 질문 소폭 수정
=> [FE] 질문 가이드 기능 구현

frontend/src/components/landing/MemberProfile/MemberProfile.tsx, frontend/src/contexts/MemberInfoProvider.tsx, frontend/src/utils/cookie.ts
closed #409 
-  로그아웃 기능 고도화
- 로그인 페이지 접근 제한 기능 구현
=> [FE] 로그아웃 기능 고도화 및 로그인시 로그인 페이지 접근 제한 기능 구현

frontend/src/components/common/Modal/Template/Alert.tsx
closed #413 
- Alert Modal 버튼 디자인 변경
이전
이후
=> [FE] Alert Modal 버튼 디자인 변경

frontend/src/hooks/common/useInput.ts
- closed #275 
- closed #270 
- input 공백 validate 추가
- 추후에 동적으로 에러메세지 뜨게 해보겠습니다. ex) 공백만 입력할 수 없습니다.
=> [FE] Input validation 추가

frontend/src/api/index.ts, frontend/src/hooks/participation/useCheckProgresses.ts, frontend/src/types/api.ts, frontend/src/utils/http.ts
- closed #423 
- 다시 시작할 시 progressId Delete 요청 로직 추가
=> [FE] ProgressId Delete 요청 추가

backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java, backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java, backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java, frontend/src/api/index.ts, frontend/src/assets/icons/ArrowIcon.tsx, frontend/src/components/board/GuideModal/GuideModal.tsx, frontend/src/components/board/PlanningForm/PlanningForm.tsx, frontend/src/components/board/RetrospectForm/RetrospectForm.tsx, frontend/src/components/board/StepContents/StepContents.tsx, frontend/src/components/board/StudyingForm/StudyingForm.tsx, frontend/src/components/board/Timer/Timer.tsx, frontend/src/components/common/Button/Button.tsx, frontend/src/components/common/Modal/Template/Alert.tsx, frontend/src/components/common/QuestionAnswer/QuestionAnswer.tsx, frontend/src/components/common/QuestionTextarea/QuestionTextarea.tsx, frontend/src/components/common/Typography/Typography.tsx, frontend/src/components/landing/Hero/Hero.tsx, frontend/src/components/landing/MemberProfile/MemberProfile.tsx, frontend/src/constants/study.ts, frontend/src/contexts/MemberInfoProvider.tsx, frontend/src/hooks/board/useRetrospectForm.ts, frontend/src/hooks/common/useInput.ts, frontend/src/hooks/participation/useCheckProgresses.ts, frontend/src/mocks/handlers/index.ts, frontend/src/pages/Landing.tsx, frontend/src/pages/StudyBoard.tsx, frontend/src/types/api.ts, frontend/src/utils/cookie.ts, frontend/src/utils/http.ts
- closed: #425 
- 1.1.1 버전 main 브랜치 머지
=> [ALL] 하루스터디 v1.1.1 배포 👏

backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
- closed #433 
- cookie의 maxAge 설정은 초 단위로 설정됩니다.
- refreshTokenLength은 milliseconds 단위이기 때문에 초 단위로 변경했습니다.
=> [BE] refreshToken 쿠키 수명 설정 시 입력 값 오류

backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java, backend/src/test/java/harustudy/backend/room/service/PomodoroRoomServiceTest.java
- closed #444 
-  비회원인 경우 참여 플로우 인수테스트 시나리오를 추가합니다.
- 회원으로 진행한 스터디 목록 조회 플로우 인수테스트 시나리오를 추가합니다.
=> [BE] 인수테스트 시나리오 추가

frontend/src/api/httpInstance.ts, frontend/src/api/index.ts, frontend/src/errors/index.ts, frontend/src/utils/cookie.ts, frontend/src/utils/http2.ts, frontend/src/utils/params.ts, frontend/src/utils/tokenStorage.ts
closed #440
- Http 클래스 구현
- http 인스턴스 구현 (refresh 토큰 로직)
- 커스텀 에러 네이밍 변경
- 쿠키 함수 네이밍 변경
=> [FE] Http 클래스 구현 및 기타 사항 리팩토링

frontend/src/api/httpInstance.ts, frontend/src/api/index.ts, frontend/src/components/create/CreateStudyForm/CreateStudyForm.tsx, frontend/src/components/participation/MemberRegister/MemberRegister.tsx, frontend/src/components/participation/ParticipationCodeInput/ParticipationCodeInput.tsx, frontend/src/hooks/create/useCreateStudy.ts, frontend/src/hooks/participation/useCheckProgresses.ts, frontend/src/hooks/participation/useParticipationCode.ts, frontend/src/hooks/participation/useRegisterProgress.ts, frontend/src/mocks/handlers/progressesHandlers.ts, frontend/src/pages/StudyPreparation.tsx
- closed #463
- useCreateStudy api 호출 로직 수정된 http 이용하여 리팩터링
- useCheckProgresses api 호출 로직 수정된 http 이용하여 리팩터링
- useParticipationCode api 호출 로직 수정된 http 이용하여 리팩터링
- useRegisterProgress api 호출 로직 수정된 http 이용하여 리팩터링
- progress delete 관련한 msw 코드 작성
- api 메서드 컨벤션 request + fetch method + 기능명으로 통일
- catch error 필요한부분 error 대신 reason으로 변경
- 아까 슬랙에 정리한거 올리면서 말했듯이 ErrorBoundary 적용할거라 일단 에러핸들링 로직을 삭제했습니다. 코드가 다 합쳐진 후 에러핸들링에 대한 작업 들어가는걸로 하면 좋을 것 같습니다.
- 에러 제외하고 정상적인 플로우는 다 잘 작동하는거 확인했습니다.
=> [FE] 개설하기 및 참여하기 플로우 API 호출 로직 리팩터링

backend/src/main/java/harustudy/backend/auth/controller/AuthController.java, backend/src/main/java/harustudy/backend/common/exception/ErrorCodeView.java
- closed: #459 
- 에러코드 명세 페이지 API Path 수정 및 path 버그 수정
=>  [BE] 에러코드 명세 페이지 API Path 수정 

backend/src/main/java/harustudy/backend/auth/controller/AuthController.java, backend/src/main/java/harustudy/backend/auth/exception/RefreshTokenNotExistsException.java, backend/src/main/java/harustudy/backend/common/exception/ExceptionMapper.java, backend/src/main/java/harustudy/backend/config/WebMvcConfig.java
- closed: #484 
- closed: #470 
- 에러코드 페이지가 Interceptor를 거치지 않도록 수정했습니다.
- 추가로 1405번에 대한 error code도 지정했습니다.
=> [BE] 에러코드 페이지에서는 Interceptor가 작동하지 않도록 수정 

backend/src/main/java/harustudy/backend/config/WebMvcConfig.java, backend/src/main/resources/templates/error-code.html
`api/resources` -> `classpath:/static/`
- closed: #487 
- 정적 자원을 찾을 수 있도록 경로를 매핑한다.
=> [BE] 정적 자원을 찾을 수 있도록 경로 매핑

README.md
close #495 
- wiki에 있는 시스템 구성도와 팀 구성을 포함했습니다.
아래와 같으며 추후 변경될 수 있습니다.
=> [ALL] README를 추가한다

backend/src/main/java/harustudy/backend/common/CachingFilter.java, backend/src/main/java/harustudy/backend/config/FilterConfig.java
close #507 
- 별도의 filter config를 통해 CachingFilter가 특정 API에서만 작동
- **후에 loggingInterceptor가 SSE 관련 기능에 동작하지 않도록 `WebMvcConfig`설정에서 URI를 조정해주어야 함.**
=> [BE] interceptor와 sse관련 로깅 문제 해결

frontend/src/components/common/Input/Input.tsx, frontend/src/components/common/Select/Select.tsx, frontend/src/components/common/Select/SelectItem.tsx, frontend/src/components/common/Select/SelectTrigger.tsx, frontend/src/components/create/CreateStudyForm/CreateStudyForm.tsx, frontend/src/components/participation/ParticipationCodeInput/ParticipationCodeInput.tsx, frontend/src/components/participation/PrticipationContents/MemberRegister/MemberRegister.tsx, frontend/src/components/participation/PrticipationContents/MemberRestart/MemberRestart.tsx, frontend/src/components/participation/PrticipationContents/ParticipationCodeCopier/ParticipationCodeCopier.tsx, frontend/src/pages/layout/StudyParticipationLayout.tsx
- #520 
- 기존 대부분 Typography를 사용했던 것들을 최소한으로 사용하도록 하고 반응형 작업했습니다.
- 개설하기, 참여하기, 준비하기 플로우 iphone 12 pro 기준으로 반응형 적용 완료했습니다.
- 768px 기준으로 Label 및 bottomText font-size를 한 단계씩 줄여줬습니다.
=> [FE] 개설하기, 참여하기, 준비하기 반응형 작업 v2

frontend/public/index.html
=> [FE] html 파일 style sheet 경로 변경

jenkins/frontend-develop.jenkinsfile
=> [FE] sourceFiles 경로 변경

backend/src/main/java/harustudy/backend/participantcode/domain/ParticipantCode.java
close #552
-  참여 코드 엔티티가 BaseEntity를 상속하도록 한다.
=> [BE] 참여 코드 엔티티가 BaseEntity를 상속하도록 한다.

jenkins/frontend-production.jenkinsfile
=> [FE] production jenkins 스크립트 변경

backend/src/main/java/harustudy/backend/participantcode/domain/ParticipantCode.java
=> [BE] ParticipantCode 관련 오류 수정

frontend/src/components/common/Button/Button.tsx
closed #582 
- Button isLoading 일 때, 중복 클릭 방지
=> [FE] Button isLoading 일 때, 중복 클릭 방지

backend/src/main/java/harustudy/backend/common/exception/ExceptionMapper.java, backend/src/main/java/harustudy/backend/participant/service/ParticipantService.java, backend/src/main/java/harustudy/backend/study/exception/StudyAlreadyStartedException.java, backend/src/test/java/harustudy/backend/participant/service/ParticipantServiceTest.java
close #576
- 이미 시작한 스터디 신규 참여 차단 로직 구현
=> [BE] 이미 시작한 스터디 신규 참여 차단 로직 구현

jenkins/backend-production2.jenkinsfile
- closed: #587 
-  scale-out 용 젠킨스 스크립트 생성한다.
=> [BE] scale-out 용 젠킨스 스크립트 생성 

frontend/src/components/mode/StudyModeContent/StudyModeContent.tsx, frontend/src/pages/CreateStudy.tsx
- closed #600 
- 버튼 제외하고 혼자 공부하기로 문구 수정
=> [FE] 학습 선택 문구 변경

frontend/src/api/index.ts, frontend/src/contexts/MemberInfoProvider.tsx, frontend/src/mocks/handlers/authHandler.ts
- closed #614
- 기존 로그아웃 시 쿠키 및 세션 스토리지 clear하는걸 세션(accessToken)스토리지를 삭제 해주고 쿠키(refreshToken)는 서버단에서 post 요청에 따라 관리하도록 변경
- msw 코드 추가
=> [FE] 로그아웃 처리 로직 변경

backend/src/test/java/harustudy/backend/view/service/ViewServiceTest.java
- closed #624 
- view API 테스트에 잘못 추가된 출력문 삭제
=> [BE] view API 테스트에 잘못 추가된 출력문 삭제

README.md, backend/.gitignore
close #636
- Readme의 시스템 구성도를 ec2 4개 버전으로 업데이트한다
=> [BE] README 업데이트

backend/src/main/java/harustudy/backend/auth/dto/UserInfo.java, backend/src/main/java/harustudy/backend/auth/exception/OauthServerException.java, backend/src/main/java/harustudy/backend/auth/exception/UserInfoFormatException.java, backend/src/main/java/harustudy/backend/auth/util/OauthUserInfoExtractor.java, backend/src/test/java/harustudy/backend/auth/dto/UserInfoTest.java
=> [BE] KAKAO UserInfo 파싱 변경

backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
close #643
- 로그아웃 시 max age를 0으로 설정한 쿠키의 적용 path를 루트("/")로 변경한다
=> [BE] 로그아웃 시의 쿠키의 path 수정

backend/src/main/java/harustudy/backend/polling/service/PollingService.java, backend/src/test/java/harustudy/backend/polling/service/PollingServiceTest.java
closed #658
- 대기방에서 방장이 나갔을 때 기존 참여자들에게 빈 배열을 응답한다.
=> [BE] 대기방에서 방장이 나갔을 때 기존 참여자들에게 빈 배열 응답

frontend/src/components/record/member/calendar/MemberRecordListModal/MemberRecordListModal.tsx
closed #I668
- max-height, overflow-y 추가
=> [FE] 달력 모달 스크롤 문제 해결

backend/src/main/java/harustudy/backend/participantcode/domain/ParticipantCode.java
- closed #675 
- 무중단 배포를 위해 `participant_code`를 `participant_code_v2`로 변경합니다.
- 변경 전
- 변경 후
=> [BE] 무중단 배포를 위한 테이블 네이밍 임시 변경

frontend/__test__/StudyPreparationPage.test.tsx, frontend/__test__/StudyRecord.test.tsx, frontend/src/api/httpInstance.ts, frontend/src/api/index.ts, frontend/src/mocks/handlers/authHandler.ts, frontend/src/mocks/handlers/contentsHandler.ts, frontend/src/mocks/handlers/participantsHandler.ts, frontend/src/mocks/handlers/pollingHandler.ts, frontend/src/mocks/handlers/queryHandler.ts, frontend/src/mocks/handlers/studiesHandler.ts
closed #677 
- api 요청 경로에 v2를 추가했습니다. 이를 위해 API_BASIC_URL 상수를 만들었습니다.
- 이에 대한 테스트 코드도 수정했습니다.(url 수정)
- 이에 대한 MSW 코드도 수정했습니다. (url 수정)
=> [FE] 프론트 무중단 배포 준비

README.md
close #682 
- README 작성
- 서비스 대문, 서비스 소개, 기술스택, 멤버
=> [ALL] 레포지토리 README 작성 완료

jenkins/frontend-admin-develop.jenkinsfile, jenkins/frontend-admin-production.jenkinsfile
=> [FE] 어드민 젠킨스 스크립트 변경

admin/src/constants/routes.ts
=> [FE] admin 경로 문제 수정

frontend/src/components/landing/MemberProfile/MemberProfile.tsx, frontend/src/components/landing/hooks/usePreFetchMemberCalendarRecord.ts, frontend/src/components/record/hooks/useMemberCalendarRecord.ts, frontend/src/components/record/hooks/useMemberListRecord.ts, frontend/src/components/record/hooks/useParticipantRecordContents.ts, frontend/src/components/record/hooks/useStudyData.ts, frontend/src/components/record/hooks/useStudyParticipants.ts
closed #693
- 비회원 프로필 문제 및 캐시 정책 수정
=> [FE] 비회원 프로필이 보이지 않는 문제

jenkins/backend-production.jenkinsfile, jenkins/backend-production2.jenkinsfile, jenkins/frontend-admin-develop.jenkinsfile, jenkins/frontend-admin-production.jenkinsfile, jenkins/frontend-develop.jenkinsfile, jenkins/frontend-production.jenkinsfile
- closed: #685
- 젠킨스 스크립트의 체크아웃 스테이지를 제거하고 젠킨스에서 태그 기반으로 설정하도록 수정
=> [ALL] 젠킨스 스크립트 체크아웃 스테이지 제거

backend/src/main/java/harustudy/backend/admin/entity/AdminSession.java, backend/src/main/java/harustudy/backend/config/WebMvcConfig.java
- 인터셉터 설정 변경 및 UUID Column 지정한다.
=> [BE] 인터셉터 설정 변경 및 UUID Column 지정

backend/src/main/java/harustudy/backend/admin/entity/Admin.java, backend/src/main/java/harustudy/backend/admin/entity/AdminSession.java, backend/src/main/java/harustudy/backend/config/WebMvcConfig.java
=> [BE] Admin 키 생성 전략 변경

backend/src/main/java/harustudy/backend/admin/controller/AdminController.java, backend/src/main/java/harustudy/backend/admin/entity/Admin.java, backend/src/main/java/harustudy/backend/admin/entity/AdminSession.java, backend/src/main/java/harustudy/backend/config/WebMvcConfig.java
=> [BE] RequestParam 속성 변경

backend/src/main/java/harustudy/backend/admin/controller/AdminController.java, backend/src/main/java/harustudy/backend/admin/entity/Admin.java, backend/src/main/java/harustudy/backend/admin/entity/AdminSession.java, backend/src/main/java/harustudy/backend/admin/service/AdminService.java, backend/src/main/java/harustudy/backend/config/WebMvcConfig.java
=> [BE] 로그인 타입 처리 방식 변경

backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
- 현재 secure 옵션으로 인해 쿠키 값을 읽을 수 없어 클라이언트에서 리프레쉬 요청이 불가능합니다
=> [HOTFIX] 쿠키 SECURE 속성 변경

backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
=> [HOTFIX] HTTP Only 제거

frontend/src/api/httpInstance.ts, frontend/src/components/lobby/StudyLobbyContents/StudyLobbyContents.tsx, frontend/src/components/progress/StudyBoard/StudyBoard.tsx, frontend/src/components/progress/StudyInfoModal/StudyInfoModal.tsx, frontend/src/hooks/common/useConfirmBerforeRouting.ts, frontend/src/utils/Http.ts
close #713 
- 하루스터디 v1.2.1 배포 🎉
=> [ALL] 하루스터디 v1.2.1 배포 🎉

backend/src/main/java/harustudy/backend/study/controller/StudyController.java, backend/src/main/java/harustudy/backend/study/dto/StudyFilterRequest.java, backend/src/main/java/harustudy/backend/study/service/StudyService.java, backend/src/test/java/harustudy/backend/integration/StudyIntegrationTest.java
- ref: #716 
이전 리팩터링 pr에 추가로 Pr요청 보냅니다.
- 어제 모쌤이 ModelAttribute알려주셨는데 동적인 쿼리 파라미터에 유연하게 대응할 수 있겠다 싶어서 적용해 봤습니다.
- 추가로 해당 관련 부분 테스트 추가해 놓고 리팩터링 했습니다.
+ 다른 api에서도 적용해 볼 수 있는 곳들도 있어보이는데 이거 괜찮으면 천천히 다른데도 적용해 보면 좋을 것 같네요!
=> [BE] 여러개의 쿼리파라미터를 ModelAttribute로 변경

backend/src/main/java/harustudy/backend/HaruStudyApplication.java
ref #715
- `@EnableScheduling` 추가 제거하여 마쌤 코드에 PR 보냅니다
=> [BE] 불필요한 코드 제거 및 리팩터링 (@EnableScheduling 제거)

backend/src/main/java/harustudy/backend/admin/controller/AdminController.java, backend/src/main/java/harustudy/backend/admin/dto/AdminParticipantCodesResponse.java, backend/src/main/java/harustudy/backend/admin/service/AdminService.java, backend/src/main/java/harustudy/backend/view/dto/CalendarStudyRecordsResponse.java, backend/src/main/java/harustudy/backend/view/dto/StudyRecordsPageResponse.java, backend/src/main/java/harustudy/backend/view/service/ViewService.java, backend/src/test/java/harustudy/backend/admin/service/AdminServiceTest.java
- closed: #703 
- 참여코드를 응답해야 하지만 참여자를 응답하고 있던 버그를 수정했습니다.
=> [BE] 어드민 페이지 참여코드 조회 버그 개선 

backend/src/main/java/harustudy/backend/HaruStudyApplication.java, backend/src/main/java/harustudy/backend/polling/controller/PollingController.java, backend/src/main/java/harustudy/backend/study/controller/StudyController.java, backend/src/main/java/harustudy/backend/study/dto/StudyFilterRequest.java, backend/src/main/java/harustudy/backend/study/service/StudyService.java, backend/src/test/java/harustudy/backend/integration/StudyIntegrationTest.java
- closed: #715 
- 사용하지 않는 `@AuthMember`와 공백 빠진 부분 넣어줬습니다
=> [BE] 불필요한 코드 제거 및 리팩터링

.github/workflows/backend-deploy.yml, .github/workflows/frontend-develop-deploy.yml, .github/workflows/frontend-main-deploy.yml
close #742
- 백엔드 Github Action CD 구현
=> [BE] 백엔드 Github Action CD 구현

.github/workflows/backend-deploy.yml
=> [BE] 백엔드 Github Action CD 구현(2)

.github/workflows/frontend-develop-deploy.yml, .github/workflows/frontend-main-deploy.yml
- closed: #748 
- workflow에서 checkout시 submodule 가져오는 설정 추가했습니다
=> [FE] github action submodule 설정 추가

.github/workflows/frontend-develop-deploy.yml, .github/workflows/frontend-main-deploy.yml
- closed: #751 
- source에 frontend 경로 추가했습니다
=> [FE] 프론트 워크플로우 경로 변경

.github/workflows/frontend-develop-deploy.yml, .github/workflows/frontend-main-deploy.yml
- CD의 SCP 과정에서 strip components 옵션의 level이 한 단계 맞지 않아 수정
=> [FE] frontend cd scp strip components level 수정
