frontend/src/App.tsx, frontend/src/components/common/Typography/Typography.stories.ts, frontend/src/components/common/Typography/Typography.tsx
closed #35
- Figma Typography 팔레트 작성
- Typography 컴포넌트 구현
- Typography 컴포넌트 스토리북 구현
=> [FE] Typography 템플릿 및 컴포넌트 구현

backend/src/main/java/harustudy/backend/BackendApplication.java, backend/src/main/java/harustudy/backend/entity/BaseTimeEntity.java, backend/src/main/java/harustudy/backend/entity/Member.java, backend/src/main/java/harustudy/backend/entity/MemberProgress.java, backend/src/main/java/harustudy/backend/entity/MemberRecord.java, backend/src/main/java/harustudy/backend/entity/ParticipantCode.java, backend/src/main/java/harustudy/backend/entity/Study.java
closed #82 
- 모든 엔티티에 등록 시간 정보를 추가한다.
- 모든 엔티티에 수정 시간 정보를 추가한다.
기존에는 각 엔티티에 생성 및 수정 시의 시간 정보가 없었습니다
현재는 시간 관련 정보만 기본으로 등록, 상속관계를 가지는 테이블의 경우 부모 테이블에만 시간 정보가 남도록 구성했습니다.
추후 생성자, 수정자에 대한 정보가 기록된다면 `BaseEntity`를 변경해야 합니다.
=> [BE] 모든 엔티티에 등록 시간, 수정 시간 정보 추가

frontend/.eslintrc, frontend/src/App.tsx, frontend/src/assets/icons/HamburgerIcon.tsx, frontend/src/components/common/Menu/Menu.stories.tsx, frontend/src/components/common/Menu/Menu.tsx, frontend/src/components/common/Menu/MenuItem.tsx, frontend/src/hooks/useOutsideClick.ts, frontend/src/styles/reset.ts
closed #45  
- Menu Component 구현
- useOutsideClick 훅 구현(참고 - https://gurtn.tistory.com/203)
```tsx
const App () => {
const ref = useOutsideClick<HTMLDivElement>(() => someFunction());
// ...
}
```
- 기존 `useRef` 사용법과 같지만 `ref`로 지정한 영역을 제외한 영역을 클릭했을 때 발생하게 되는 함수를 인자로 넘깁니다.
=> [FE] Menu Component 구현

backend/src/main/java/harustudy/backend/entity/Study.java, backend/src/test/java/harustudy/backend/service/ParticipateServiceTest.java
- closed #115 
- Study 저장시 MemberProgress를 Study.add 했으나 MemberProgress가 영속화 되지 않아서 Study.MemberProgresses에 cascade.Persist 적용했습니다. Cascade를 걸지 말고 서비스에서 로직을 수행하자는 의견이 있었으나 닉네임 중복 검증 로직도 다 서비스로 빼지 않으면 에러가 발생해서 일단 cascade를 적용하는 방향으로 해결했습니다.
=> [BE] 스터디 참여시 MemberProgress 영속화 되지 않는 문제 수정

jenkins/backend-prod.jenkinsfile
- closed #117 
-  ssh publisher로 원격 스크립트를 실행하면 stdoutput이 닫히거나 timeout이 발생할 때까지 스크립트가 닫히지 않음. 그래서 script로 백그라운드 작업을 하면 모든 output을 redirect 해서 스크립트가 종료되도록 수정.
=> [BE] 젠킨스 무한 출력 스트림 리다이렉션

backend/src/main/java/harustudy/backend/config/OpenApiConfiguration.java, backend/src/main/java/harustudy/backend/content/controller/ContentController.java, backend/src/main/java/harustudy/backend/content/dto/CurrentCyclePlanResponse.java, backend/src/main/java/harustudy/backend/content/service/ContentService.java, backend/src/test/java/harustudy/backend/integration/FindRoomIntegrationTest.java, backend/src/test/java/harustudy/backend/progress/service/ProgressServiceTest.java
- closed: #167 
- api 문서에 현재 사이클 조회 응답 형태가 아래 사진에서 "plan"이 빠져있어 DTO가 아닌 Map<String, String>을 응답하도록 수정했습니다.
=> [BE] 현재 사이클 조회 응답 수정

frontend/src/components/common/Select/Select.stories.tsx, frontend/src/components/common/Select/SelectItem.tsx, frontend/src/components/common/Select/SelectList.tsx, frontend/src/components/common/Select/SelectTrigger.tsx
=> [FE] Select Height 수정 및 border 수정

frontend/src/hooks/board/useStudyBoard.ts, frontend/src/hooks/board/useTimer.ts
closed #251 
- 타이머 시간 느리게 가는 버그 수정
- 진행 페이지에서 memberId 혹은 studyId가 잘못되었을 경우 무한 로딩에 빠지는 문제 수정
=> [FE] 브라우저 비활성탭일 때 타이머 시간 느리게 가는 버그 수정

backend/src/main/java/harustudy/backend/member/service/MemberService.java
- closed: #257 
- 404와 code:1000이 아닌 nickname에 Null을 반환하도록 변경
=> [BE] memberId가 이미 있지만 다른 스터디를 참여할 때 null이 아닌 404내려주는 문제

frontend/src/api/index.ts, frontend/src/components/record/MemberRecord/MemberRecord.tsx, frontend/src/components/record/MemberRecordList/MemberRecordList.tsx, frontend/src/components/record/RecordContents/RecordContents.tsx, frontend/src/hooks/record/useMemberRecord.ts, frontend/src/hooks/record/useStudyRecord.ts, frontend/src/mocks/handlers/studyRecordHandlers.ts
closed #261
- hooks/record 폴더에 `useStudyRecord`, `useMemberRecord` 훅을 만들어 api 통신 로직을 분리
- 스터디 기록 페이지와 관련된 api를 `v2` 로 적용 및 msw 수정
=> [FE] 스터디 기록 페이지 API 훅 분리 및 v2 적용

frontend/src/pages/Login.tsx
closed #330 
```ts
const REDIRECT_URI = '/auth?provider=google';
const baseUri = `${window.location.protocol}//${window.location.host}`;
```
위와 같이 base uri를 가져와 oauth redirect uri 설정
=> [FE] OAuth 리다랙트 경로 상대 경로로 적용

backend/src/main/java/harustudy/backend/member/controller/MemberController.java, backend/src/main/java/harustudy/backend/member/service/MemberService.java, backend/src/test/java/harustudy/backend/member/service/MemberServiceTest.java
- closed #383 
- 멤버 프로필 조회 시 불필요한 memberId를 담지 않도록 수정
=> [BE] 멤버 프로필 조회 시 불필요한 memberId를 담지 않도록 수정

backend/src/main/java/harustudy/backend/auth/domain/RefreshToken.java, backend/src/main/java/harustudy/backend/auth/repository/RefreshTokenRepository.java, backend/src/main/java/harustudy/backend/auth/service/AuthService.java
- close #388 
- Member 영속화 시 필드 저장 순서가 다른 문제를 해결한다.
- refresh token이 여러 번 저장되는 문제를 해결한다.
=> [BE] Member 영속화 시 필드 순서 조정 및 refresh token이 여러번 저장되는 문제 해결 

backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
- close #395 
- `/api/refresh` 접근 시에도 refresh token cookie path 설정을 '/'로 한다.
=> [BE] refresh 요청 시에도 쿠키 path '/' 으로 설정

backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java, backend/src/test/java/harustudy/backend/progress/service/PomodoroProgressServiceTest.java
- closed #376 
검증로직의 부재로 현재 다른 스터디의 '기록 조회' 페이지가 열람이 가능한데, 멤버가 스터디에 참여하지 않았다면 타인의 진행도를 볼 수 없게 수정했습니다. 이에 따라 테스트도 몇개 추가했습니다.
=> [BE] 멤버가 스터디에 참여하지 않았다면 타인의 진행도를 볼 수 없게 수정 

backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java, backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java, backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java
close #408 
- '/api/studies/{studyId}/progresses/{progressId}'를 통해 이미 존재하는 progress 및 content를 삭제하도록 한다.
=> [BE] 스터디에 학습 기록이 존재할 때 처음부터 진행하는 플로우에서 발생하는 문제

frontend/src/components/waiting/StudyWaitingMembers/StudyWaitingMembers.tsx, frontend/src/components/waiting/StudyWaitingMembers/StudyWaitingMemebers.stories.tsx
- closed #467 
- StudyWaitingMembers 컴포넌트 구현
- StudyWaitingMembers 스토리북 작성
=> [FE] 스터디 대기 인원 컴포넌트 UI 구현

frontend/.eslintrc, frontend/src/App.tsx, frontend/src/components/progress/hooks/useStudyBoard.ts, frontend/src/contexts/MemberInfoProvider.tsx, frontend/src/contexts/StudyProgressProvider.tsx, frontend/src/hooks/api/useFetch.ts, frontend/src/hooks/api/useMutation.ts
#510과 연관된 이슈이지만 Auth로직은 아직 안되어있어서 closed는 안하겠습니다.
- useFetch 옵션(enabled, onSuccess, onError) 추가
- useMutation 옵션(onSuccess, onError) 추가
- MemberInfoProvider 로직 변경
useFetch의 enabled 옵션을 추가했습니다. MemberInfo도 MemberInfo인데, 이 옵션 추가도 리팩토링에 매우 중요할 것 같아서 PR을 빠르게 올립니다.
이 옵션은 useFetch를 순차적으로 실행 할 수 있게 도와줍니다. enabled가 false면 fetch를 실행 안하고 있다가, true로 바뀌면 fetch를 실행해요.
다음과 같이 사용할 수 있습니다.
```jsx
const memberInfo = useMemberInfo(); // memberInfo의 타입은 MemberInfo | null
const { ... } = useFetch(() => {requestFunc()}, {enabled: !!memberInfo});
```
이렇게 사용하면 memberInfo가 null일 때는 fetch가 되지 않다가, memberInfo 데이터가 들어오면 그제서야 fetch 실행을 합니다. 이렇게 하면 데이터 순서 보장을 할 수 있겠죠?
바뀐 MemberInfo와 useFetch가 얼른 올라가야 추후 코드 병합하기도 좋을 것 같아 일단 MemberInfo만 우선적으로 올립니다.
지금은 MemberInfoProvider가 잘 작동하는지는 모르겠어요.. 일단 반영해보고 에러가 난다면 추후 수정해보시죠.
=> [FE] MemberInfoProvider 로직 수정 및 useFetch, useMutation 옵션 추가

frontend/src/api/httpInstance.ts, frontend/src/contexts/MemberInfoProvider.tsx
closed #538 
- Auth 페이지일 경우 초기 멤버 fetching 안하도록 수정
=> [FE] 로그인 페이지(Auth) 요청 순서 보장하지 못하는 버그

frontend/src/components/landing/BugReportingLink/BugReportingLink.tsx, frontend/src/components/landing/ChattingLink/ChattingLink.tsx, frontend/src/components/landing/LoginModalContents/LoginModalContents.tsx
closed #547 
- 모바일 환경에서의 구글 로그인 아이콘 위치 수정
=> [FE] 모바일 환경에서의 구글 로그인 아이콘 위치 수정

backend/src/main/java/harustudy/backend/participant/domain/Participant.java, backend/src/main/java/harustudy/backend/participant/service/ParticipantService.java, backend/src/test/java/harustudy/backend/content/repository/ContentRepositoryTest.java, backend/src/test/java/harustudy/backend/content/service/ContentServiceTest.java, backend/src/test/java/harustudy/backend/integration/ContentIntegrationTest.java, backend/src/test/java/harustudy/backend/integration/IntegrationTest.java, backend/src/test/java/harustudy/backend/integration/MemberIntegrationTest.java, backend/src/test/java/harustudy/backend/integration/ParticipantIntegrationTest.java, backend/src/test/java/harustudy/backend/integration/PollingIntegrationTest.java, backend/src/test/java/harustudy/backend/integration/StudyIntegrationTest.java, backend/src/test/java/harustudy/backend/integration/ViewIntegrationTest.java, backend/src/test/java/harustudy/backend/member/service/MemberServiceTest.java, backend/src/test/java/harustudy/backend/participant/service/ParticipantServiceTest.java, backend/src/test/java/harustudy/backend/participantcode/service/ParticipantCodeServiceTest.java, backend/src/test/java/harustudy/backend/polling/service/PollingServiceTest.java, backend/src/test/java/harustudy/backend/testutils/EntityManagerUtil.java
- closed: #591 
- 기존에 flush & clear하는 메서드를 테스트 내에서 따로 만들어줘서 중복이 많았어서 EntityManagerUtil로 분리했습니다
=> [BE] participant에서 content 생성 로직 분리

backend/src/main/java/harustudy/backend/auth/controller/AuthController.java, backend/src/main/java/harustudy/backend/auth/repository/RefreshTokenRepository.java, backend/src/main/java/harustudy/backend/auth/service/AuthService.java, backend/src/main/java/harustudy/backend/auth/service/OauthLoginFacade.java, backend/src/test/java/harustudy/backend/auth/service/AuthServiceTest.java, backend/src/test/java/harustudy/backend/integration/AuthIntegrationTest.java, backend/src/test/java/harustudy/backend/integration/IntegrationTest.java
=> [BE] 로그아웃 기능 및 인증 관련 정비

backend/src/main/java/harustudy/backend/study/repository/StudyRepository.java, backend/src/main/java/harustudy/backend/study/service/StudyService.java
- closed: #622 
- 기존 서비스 로직에서 발생하는 N+1 문제 개선
=> [BE] 기존 서비스 로직에서 발생하는 N+1 문제 개선

frontend/src/components/common/Footer/Footer.tsx, frontend/src/components/record/hooks/useMemberListRecord.ts, frontend/src/components/record/member/period/EmptyMemberRecord/EmptyMemberRecord.tsx, frontend/src/components/record/member/period/MemberRecordPeriod/MemberRecordPeriod.tsx, frontend/src/mocks/handlers/queryHandler.ts, frontend/src/mocks/mockData.ts
closed #628 
- 기록 목록 조회 전체 페이지 버그 수정: totalPages은 1부터 시작합니다. 이를 생각하지 못하고 로직을 작성하여 수정합니다.
- 기록이 없는 경우 Pagination 버튼 제거
- 기록이 없는 경우 보여지는 EmptyMemberRecord 개선
- 문구를 "완료한 스터디가 없어요. 스터디를 시작해 보세요."로 수정 -> 괜찮은 문구 있으면 추천해주세요.
- 기존 스터디 개설하기, 스터디 참여하기 버튼을 스터디 시작하기 버튼으로 대체함. 버튼을 통해 `/mode`로 이동
- 반응형 추가
=> [FE] 목록 조회 totalPages 오류 수정 및 EmptyMemberRecord 개선

frontend/src/components/landing/LoginModalContents/LoginModalContents.tsx, frontend/src/styles/color.ts, frontend/src/types/auth.ts
closed #632 
- 카카오 로그인 기능 추가
카카오 말풍선 svg을 찾지 못해 기존 사용하고 있던, chat icon으로 사용합니다. 추후에 좋은 svg, png가 있다면 업데이트할게요. 카카오 개발자 센터에서 제공하는 로그인 관련 이미지는 각각 분리되어 있지 않고 모두 하나의 이미지로 만들어져 있어 사용하기에 불편함이 있습니다. 혹시 이에 대해 좋은 팁이 있다면 알려주세요! 😁
=> [FE] 카카오 로그인 기능 추가

jenkins/backend-develop.jenkinsfile, jenkins/frontend-develop.jenkinsfile
- closed: #635 
- 프론트 파일은 production 서버로 전송
- 백엔드 Dev 파일은 production2 서버로 전송
=> [ALL] 서버 분리로 인한 젠킨스 스크립트의 서버 설정 변경

backend/src/main/java/harustudy/backend/auth/domain/oauth/GoogleOauthClient.java, backend/src/main/java/harustudy/backend/auth/domain/oauth/KakaoOauthClient.java, backend/src/main/java/harustudy/backend/auth/domain/oauth/OauthClient.java, backend/src/main/java/harustudy/backend/auth/domain/oauth/OauthClients.java
closed #648
AS-IS
``` java
@Component
public class OauthClients {
private final Map<String, OauthClient> clientMappings;
public OauthClients(List<OauthClient> clientMappings) {
this.clientMappings = clientMappings.stream()
.collect(Collectors.toMap(OauthClient::getProviderName, Function.identity()));
}
```
일급 컬렉션인 OauthClients가 생성 시점에 필드로 가지고 있을 구현체들의 ProviderName을 getter를 사용해 참조합니다
TO-BE
``` java
@RequiredArgsConstructor
@Component
public class OauthClients {
private final List<OauthClient> oauthClients;
```
일급 컬렉션은 리스트로 구현체들을 자동 주입받게 하고
OAuthClient 인터페이스에 getter를 넣어두는 대신 boolean을 반환하는 supports()를 만들어 특정 provider를 처리 가능한지 외부에서 물어보도록 변형합니다
성능적으로는 map을 만들어두는 것이 좋으나 비용 차이가 크지 않고 객체지향적인 코드는 후자여서 제안해봅니다
=> [BE] 소셜 로그인 로직 개선

backend/src/main/java/harustudy/backend/HaruStudyApplication.java, backend/src/main/resources/application-develop.yml, backend/src/main/resources/application-production.yml, backend/src/main/resources/application.yml
-closed: #661 
- springboot 설정과 jpa 설정으로 jvm 타임존을 kst로 바꿔줬습니다\
- jpa 설정을 하지 않으면 db에 들어가는 created_date같은 시간이 그대로여서 jpa 설정도 필요하네요
서버 시간
db 시간
=> [BE] dev, prod 서버 시간 변경

backend/src/main/java/harustudy/backend/content/service/ContentService.java, backend/src/test/java/harustudy/backend/content/service/ContentServiceTest.java
- closed #659
- 한 사이클 내에서 계획 단계를 작성하지 않았어도 회고 단계를 작성할 수 있도록 수정
=> [BE] 목표 작성 없이 방장이 강제로 다음 단계로 넘어가면 studyStep이 적절하지 않다고 표시되는 문제 수정

frontend/src/api/index.ts, frontend/src/components/lobby/ParticipantList/ParticipantList.tsx, frontend/src/components/lobby/hooks/useStudyLobby.ts, frontend/src/components/participation/PrticipationContents/MemberRestart/MemberRestart.tsx, frontend/src/components/progress/ProgressPolling/ProgressPolling.tsx, frontend/src/components/progress/Sidebar/Sidebar.tsx, frontend/src/components/progress/StudyBoard/StudyBoard.tsx, frontend/src/components/progress/StudyInfoModal/StudyInfoModal.tsx, frontend/src/types/api.ts
closed #651 
- 스터디 종료시 스터디원 기록페이지로 이동하도록 수정
- 스터디원 제출 여부 조회 폴링으로 전환
- 스터디 나가기 기능 구현
- 나가기 api 요청은 보내지 않고, 랜딩 페이지로 라우팅 해주는 로직만 넣어줬습니다.
- 방장이 나갔을 때 api 요청을 하면 예외 사항이 엄청 많더라구요. 이 부분 너무 복잡해질 것 같아서 일단 api 요청은 해주지 않았습니다.
- participantId 타입 통일화
- participantId가 어디서는 string이고, 어디서는 number라서 모두 string으로 바꿔줬습니다.
=> [FE] 스터디 동기화 기능 버그 수정 및 추가 기능 구현

backend/src/main/java/harustudy/backend/auth/controller/AuthController.java, backend/src/main/java/harustudy/backend/common/exception/ErrorCodeView.java, backend/src/main/java/harustudy/backend/config/FilterConfig.java, backend/src/main/java/harustudy/backend/config/WebMvcConfig.java, backend/src/main/java/harustudy/backend/content/controller/ContentController.java, backend/src/main/java/harustudy/backend/member/controller/MemberController.java, backend/src/main/java/harustudy/backend/participant/controller/ParticipantController.java, backend/src/main/java/harustudy/backend/participantcode/controller/ParticipantCodeController.java, backend/src/main/java/harustudy/backend/participantcode/domain/ParticipantCode.java, backend/src/main/java/harustudy/backend/polling/controller/PollingController.java, backend/src/main/java/harustudy/backend/study/controller/StudyController.java, backend/src/main/java/harustudy/backend/view/controller/ViewController.java, backend/src/main/resources/templates/error-code.html, backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java, backend/src/test/java/harustudy/backend/integration/AuthIntegrationTest.java, backend/src/test/java/harustudy/backend/integration/ContentIntegrationTest.java, backend/src/test/java/harustudy/backend/integration/IntegrationTest.java, backend/src/test/java/harustudy/backend/integration/MemberIntegrationTest.java, backend/src/test/java/harustudy/backend/integration/ParticipantIntegrationTest.java, backend/src/test/java/harustudy/backend/integration/PollingIntegrationTest.java, backend/src/test/java/harustudy/backend/integration/StudyIntegrationTest.java, backend/src/test/java/harustudy/backend/integration/ViewIntegrationTest.java
- closed #652 
- 무중단 배포 시나리오 설계에 따른 API 버저닝 완료
- 기존 테스트 중 인수테스트와 통합 테스트 일부는 수정해서 살려두는 것보다 disabled 처리 해두는 게 나중에 버저닝을 제거할 때 더 편할 것 같다고 판단했습니다. 
- 설계된 무중단 배포 시나리오 정리 및 공유
- 팀 내 검토가 마무리 되면 더 정제해서 위키 업로드 해보도록 하겠습니다.
<br/>
폴링을 통한 스터디 동시 진행 기능이 추가되면서 사용자 별 서비스 버전 차이로 인한 오류 상황들을 방지하고 사용자로 하여금 배포 과정에서 의도치 않은 불편함을 경험하지 않도록 무중단 배포 과정을 설계한다.
<br/>
| 프론트엔드                                                                  | 백엔드                                                                        |
|:--------------------------------------------------------------------------- |:----------------------------------------------------------------------------- |
| 1. 스터디 생성, 참여 버튼을 비활성한 프론트 파일 배포 (V1 -> V1.5)          | -                                                                             |
| - …
=> [BE] 스터디 동시 진행 기능 업데이트를 위한 무중단 배포 준비

backend/src/main/java/harustudy/backend/auth/service/AuthService.java, backend/src/main/java/harustudy/backend/member/repository/MemberRepository.java, backend/src/test/java/harustudy/backend/auth/service/AuthServiceTest.java
- closed: #640 
- 이메일 기반으로 멤버를 찾지 않고 이메일과 로그인 타입을 기반으로 멤버를 찾습니다.
=> [BE] 이메일 기반으로 Oauth User를 찾는 로직 변경

frontend/src/components/progress/StudyBoard/StudyBoard.tsx, frontend/src/styles/common.ts
close #645 
- 실제 innerHeight를 측정한 글로벌 css 변수(--vh) 추가
- 진행페이지에 적용
하단 버튼이 사파리 주소창에 짤리고 스크롤이 생긴다
하단 버튼이 잘 보인다
=> [FE] 아이폰 사파리 접속시 화면 짤리는 문제 해결

frontend/src/components/common/Modal/Template/Alert.tsx, frontend/src/components/common/Modal/Template/Confirm.tsx, frontend/src/components/common/Typography/Typography.tsx, frontend/src/components/lobby/StudyLobbyContents/StudyLobbyContents.tsx, frontend/src/components/progress/PlanningForm/PlanningForm.tsx, frontend/src/components/progress/RetrospectForm/RetrospectForm.tsx, frontend/src/components/progress/StudyBoard/StudyBoard.tsx, frontend/src/components/progress/StudyInfoModal/StudyInfoModal.tsx, frontend/src/contexts/ModalProvider.tsx, frontend/src/hooks/common/useRouteBlocker.ts, frontend/src/styles/common.ts
close #650 
- Confirm Modal 컴포넌트 구현
- useModal의 openConfirm 함수를 사용하여 사용하면 됩니다.(openAlert과 동일하게 사용)
- 브라우저의 기본 confirm을 사용하는 로직을 해당 컴포넌트로 대체하도록 했습니다.
- useConfirmBeforeRouting 훅 구현
- 라우팅을 하기 전, Confirm 모달을 띄워서 정말로 라우팅을 할건지 물어보는 기능을 수행하는 훅입니다
=> [FE] Modal Confirm 컴포넌트 구현

frontend/src/components/lobby/StudyLobbyContents/StudyLobbyContents.tsx, frontend/src/components/progress/StudyInfoModal/StudyInfoModal.tsx
- dev 서버에서 확인해보니 아직 모달 킨 상태로 스터디가 종료되었을 때 404로 넘어가는 버그가 완전히 해결되지 않아서 다시 수정 후 PR 보냅니다.
- 모달에서는 DOM 위치 때문에 에러 발생시 글로벌 에러바운더리가 적용이 안되고, 곧바로 에러페이지가 떠요.
- 그래서 StudyInfoModal에서 useFetch의 errorBoundary 옵션을 false로 설정해줬습니다.
- 추가로 의미없는 console.log 제거해줬어용
=> [FE] StudyInfoModal 컴포넌트 errorBoundary 속성 false로 설정

.github/workflows/backend-build-test.yml
close #722
workflow_dispatch는 수동으로 지정한 워크플로우를 돌리는 기능인데,
구문만 들어가있고 어떤 동작은 할 지 명시가 안 되어있어서 아예 불필요한 구문인 것 같아요
자잘하긴 한데 본 김에 없애면 어떨까 해서 올립니다
어떤 기능인지 참고하시라고 링크 올려용
https://glebbahmutov.com/blog/run-and-trigger-github-workflow/
=> [BE] CI에서 사용하지 않는 workflow_dispatch 내용 제거 #722

backend/src/main/java/harustudy/backend/content/service/ContentService.java, backend/src/main/java/harustudy/backend/participant/domain/Participant.java, backend/src/main/java/harustudy/backend/participant/repository/ParticipantRepository.java, backend/src/main/java/harustudy/backend/participant/service/ParticipantService.java, backend/src/main/java/harustudy/backend/polling/controller/PollingController.java, backend/src/main/java/harustudy/backend/polling/service/PollingService.java, backend/src/main/java/harustudy/backend/study/domain/Study.java, backend/src/main/java/harustudy/backend/study/repository/StudyRepository.java, backend/src/main/java/harustudy/backend/study/service/StudyService.java, backend/src/main/java/harustudy/backend/view/service/ViewService.java
- closed: #721 
- 서비스 로직 개선, 중복 제거
- 가독성 개선
- 사용하지 않는 메소드 정리
=>  [BE] 서비스 중복 로직 제거 및 캡슐화

backend/src/main/resources/console-appender.xml, backend/src/main/resources/logback-spring.xml
- closed #732 
- 로컬에서 default 프로필로 WAS 실행 시 콘솔에 로깅이 출력되도록 수정했습니다.
- 기존 로깅 경로가 `/backend/logs/production/...` 에서 `/logs/...`로 수정되었습니다.
=> [BE] 로깅 파일 저장 경로 변경

.github/workflows/frontend-develop-deploy.yml, .github/workflows/frontend-main-deploy.yml
- closed: #739 
- 프론트 cd용 파일 2개 만들었습니다.
- 기존에 존재하던 workflow는 ci 테스트용이고 이번에 추가된 것은 직접 빌드 눌러서 수동으로 cd 돌리도록 만들었습니다.
- **주의사항** : 수동으로 배포시 브랜치를 선택해야 하는데 이 때 잘 골라야 합니다.
=> [FE] cd용 github action workflow 추가

backend/src/main/java/harustudy/backend/content/service/ContentService.java, backend/src/main/java/harustudy/backend/participant/domain/Participant.java, backend/src/test/java/harustudy/backend/content/service/ContentServiceTest.java
- closed #757 
- 같은 스터디 참여 인원 간에는 서로 스터디 기록 조회가 가능해야 하는데 과거 리팩토링 PR에서 검증 부분이 잘못 수정된 부분이 있었습니다. 이를 수정했습니다. 
- 스터디에 참여하지 않은 인원이 스터디 참여 인원의 기록을 조회하려고 하면 권한 오류가 발생하도록 했습니다.
- 같은 실수가 반복되지 않도록 스터디 기록 조회 관련 service 테스트를 추가했습니다.
=> [BE] 같은 스터디 진행 이후 다른 멤버 스터디 기록이 조회되지 않는 오류 수정
